/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.latihangui;

/**
 *
 * @author Asus
 */
public class latihan_Gui extends javax.swing.JFrame {

    /**
     * Creates new form latihan_Gui
     */
    public latihan_Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usname = new javax.swing.JLabel();
        passw = new javax.swing.JLabel();
        tfUsName = new javax.swing.JTextField();
        tfPassw = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usname.setText("username");

        passw.setText("password");

        tfUsName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsNameActionPerformed(evt);
            }
        });

        tfPassw.setText("jPasswordField1");
        tfPassw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPasswActionPerformed(evt);
            }
        });

        jButton1.setText("Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passw)
                            .addComponent(usname))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPassw)
                            .addComponent(tfUsName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton1)))
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usname)
                    .addComponent(tfUsName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passw)
                    .addComponent(tfPassw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPasswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPasswActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPasswActionPerformed

    private void tfUsNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfUsNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(latihan_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(latihan_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(latihan_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(latihan_Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new latihan_Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JButton btnLogin2;
    private javax.swing.JButton btnLogin3;
    private javax.swing.JButton btnLogin4;
    private javax.swing.JButton btnLogin5;
    private javax.swing.JButton btnLogin6;
    private javax.swing.JButton btnLogin7;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel labelPassWord;
    private javax.swing.JLabel labelPassWord1;
    private javax.swing.JLabel labelPassWord2;
    private javax.swing.JLabel labelPassWord3;
    private javax.swing.JLabel labelPassWord4;
    private javax.swing.JLabel labelPassWord5;
    private javax.swing.JLabel labelPassWord6;
    private javax.swing.JLabel labelPassWord7;
    private javax.swing.JLabel labelUserName;
    private javax.swing.JLabel labelUserName1;
    private javax.swing.JLabel labelUserName2;
    private javax.swing.JLabel labelUserName3;
    private javax.swing.JLabel labelUserName4;
    private javax.swing.JLabel labelUserName5;
    private javax.swing.JLabel labelUserName6;
    private javax.swing.JLabel labelUserName7;
    private javax.swing.JPasswordField passWord;
    private javax.swing.JPasswordField passWord1;
    private javax.swing.JPasswordField passWord2;
    private javax.swing.JPasswordField passWord3;
    private javax.swing.JPasswordField passWord4;
    private javax.swing.JPasswordField passWord5;
    private javax.swing.JPasswordField passWord6;
    private javax.swing.JPasswordField passWord7;
    private javax.swing.JLabel passw;
    private javax.swing.JPasswordField tfPassw;
    private javax.swing.JTextField tfUsName;
    private javax.swing.JTextField userName;
    private javax.swing.JTextField userName1;
    private javax.swing.JTextField userName2;
    private javax.swing.JTextField userName3;
    private javax.swing.JTextField userName4;
    private javax.swing.JTextField userName5;
    private javax.swing.JTextField userName6;
    private javax.swing.JTextField userName7;
    private javax.swing.JLabel usname;
    // End of variables declaration//GEN-END:variables
}
